!autogenerated-by:     DAG-Edit version 1.418
!saved-by:             gwg
!date:                 Fri Sep 03 16:32:00 BST 2004
!version: $Revision: 1.1 $
!type: % is_a is a
!type: < part_of Part of
!GO_slim_name: yeast go_slim
!GO_slim_authors: SGD curators
!GO_slim_author_contact: yeast-curator@genome.stanford.edu
$Gene_Ontology ; GO:0003673
 %biological_process ; GO:0008150
  %amino acid and derivative metabolism ; GO:0006519
  %biological_process unknown ; GO:0000004
  %budding ; GO:0007114
  %carbohydrate metabolism ; GO:0005975
  %cell cycle ; GO:0007049 ; synonym:cell-division cycle
   <meiosis ; GO:0007126
  %cell homeostasis ; GO:0019725
  %cell wall organization and biogenesis ; GO:0007047
  %coenzyme and prosthetic group metabolism ; GO:0006731
  %conjugation ; GO:0000746
  <cytokinesis ; GO:0000910 ; Reactome:68884 ; synonym:cell division
  %DNA metabolism ; GO:0006259
  %electron transport ; GO:0006118 ; synonym:electron transfer
  %energy pathways ; GO:0006091
   %cellular respiration ; GO:0045333 ; synonym:oxidative metabolism ; synonym:respiration
  %lipid metabolism ; GO:0006629
  %membrane organization and biogenesis ; GO:0016044
  %morphogenesis ; GO:0009653
   %pseudohyphal growth ; GO:0007124
  %nuclear organization and biogenesis ; GO:0006997, GO:0048287 ; synonym:nucleus organization and biogenesis
  %organelle organization and biogenesis ; GO:0006996
   %cytoskeleton organization and biogenesis ; GO:0007010
  %protein biosynthesis ; GO:0006412, GO:0006416, GO:0006453
  %protein catabolism ; GO:0030163 ; synonym:protein degradation
  %protein modification ; GO:0006464
  %response to stress ; GO:0006950
  %ribosome biogenesis and assembly ; GO:0042254
  %RNA metabolism ; GO:0016070
  %signal transduction ; GO:0007165
  %sporulation ; GO:0030435
  %transcription ; GO:0006350 ; Reactome:74159
  %transport ; GO:0006810
   %vesicle-mediated transport ; GO:0016192, GO:0006899 ; synonym:nonselective vesicle transport
  %vitamin metabolism ; GO:0006766
 %cellular_component ; GO:0005575
  <bud ; GO:0005933
  <cell cortex ; GO:0005938
  <cell wall ; GO:0005618
  %cellular_component unknown ; GO:0008372
  <chromosome ; GO:0005694
  <cytoplasm ; GO:0005737
   <cytoplasmic vesicle ; GO:0016023
   <cytoskeleton ; GO:0005856
   <endoplasmic reticulum ; GO:0005783 ; synonym:ER
   <Golgi apparatus ; GO:0005794 ; synonym:Golgi complex ; synonym:Golgi ribbon
   <microtubule organizing center ; GO:0005815 ; synonym:MTOC ; synonym:microtubule organizing centre
   <mitochondrion ; GO:0005739
    <mitochondrial membrane ; GO:0005740 % membrane ; GO:0016020
   <ribosome ; GO:0005840
   <vacuole ; GO:0005773
  %extracellular ; GO:0005576
  <membrane ; GO:0016020
   %endomembrane system ; GO:0012505
   %mitochondrial membrane ; GO:0005740 < mitochondrion ; GO:0005739
   %plasma membrane ; GO:0005886 ; synonym:bacterial inner membrane ; synonym:cell membrane ; synonym:cytoplasmic membrane ; synonym:plasmalemma
  <membrane fraction ; GO:0005624
  <nucleus ; GO:0005634
   <nucleolus ; GO:0005730
  <peroxisome ; GO:0005777
  <site of polarized growth ; GO:0030427
 %molecular_function ; GO:0003674
  %DNA binding ; GO:0003677
  %enzyme regulator activity ; GO:0030234 ; synonym:enzyme modulator
  %helicase activity ; GO:0004386 ; Reactome:109879 ; Reactome:111307 ; Reactome:117604 ; Reactome:117605 ; Reactome:120688 ; Reactome:72598 ; Reactome:72599
  %hydrolase activity ; GO:0016787 ; EC:3.-.-.-
   %peptidase activity ; GO:0008233 ; EC:3.4.-.- ; synonym:hydrolase\, acting on peptide bonds ; synonym:peptide hydrolase ; synonym:protease
  %isomerase activity ; GO:0016853 ; EC:5.-.-.-
  %ligase activity ; GO:0016874 ; EC:6.-.-.-
  %lyase activity ; GO:0016829 ; EC:4.-.-.-
  %molecular_function unknown ; GO:0005554
  %motor activity ; GO:0003774
  %oxidoreductase activity ; GO:0016491 ; EC:1.-.-.- ; synonym:redox activity
  %phosphoprotein phosphatase activity ; GO:0004721 ; EC:3.1.3.16 ; MetaCyc:3.1.3.16-RXN ; Reactome:113432 ; Reactome:113757 ; Reactome:115322 ; Reactome:115328 ; Reactome:115332 ; Reactome:117849 ; Reactome:117855 ; Reactome:117859 ; Reactome:117862 ; Reactome:120480 ; Reactome:120488 ; Reactome:122808 ; Reactome:122814 ; Reactome:122818 ; Reactome:124864 ; Reactome:124870 ; Reactome:69198 ; Reactome:69262 ; Reactome:69735 ; Reactome:69742 ; synonym:protein phosphatase activity
  %protein binding ; GO:0005515
  %protein kinase activity ; GO:0004672 ; EC:2.7.1.37 ; MetaCyc:PROTEIN-KINASE-RXN
  %RNA binding ; GO:0003723
  %signal transducer activity ; GO:0004871
  %structural molecule activity ; GO:0005198
  %transcription regulator activity ; GO:0030528
  %transferase activity ; GO:0016740 ; EC:2.-.-.-
   %nucleotidyltransferase activity ; GO:0016779 ; EC:2.7.7.-
  %translation regulator activity ; GO:0045182
  %transporter activity ; GO:0005215
